# Generated by Django 3.0.5 on 2021-06-01 08:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('test_app', '0004_auto_20210601_1332'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='genre',
        ),
    ]
