# Generated by Django 3.0.5 on 2021-06-01 09:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('test_app', '0006_book_genre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pageswritten',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='author_wrote', to='test_app.Author'),
        ),
        migrations.AlterField(
            model_name='pageswritten',
            name='book',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='books_written', to='test_app.Book'),
        ),
        migrations.CreateModel(
            name='BookGenre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='test_app.Book')),
                ('genre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='test_app.Genre')),
            ],
        ),
    ]
