# Generated by Django 3.0.5 on 2021-06-01 11:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('test_app', '0008_auto_20210601_1526'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BookGenre',
        ),
    ]
